// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Get() {
  return window['go']['services']['appSettingsService']['Get']();
}

export function Startup(arg1) {
  return window['go']['services']['appSettingsService']['Startup'](arg1);
}

export function Update(arg1, arg2) {
  return window['go']['services']['appSettingsService']['Update'](arg1, arg2);
}
