// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function ExploreDemo():Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopStream():Promise<void>;
