// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BindSessionToTab(arg1, arg2) {
  return window['go']['services']['ClientService']['BindSessionToTab'](arg1, arg2);
}

export function CommitDocs(arg1, arg2, arg3) {
  return window['go']['services']['ClientService']['CommitDocs'](arg1, arg2, arg3);
}

export function GenerateDocs(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['services']['ClientService']['GenerateDocs'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GenerateDocsFromBranch(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['services']['ClientService']['GenerateDocsFromBranch'](arg1, arg2, arg3, arg4, arg5);
}

export function GetAvailableTabSessions(arg1) {
  return window['go']['services']['ClientService']['GetAvailableTabSessions'](arg1);
}

export function IsSessionInTab(arg1, arg2) {
  return window['go']['services']['ClientService']['IsSessionInTab'](arg1, arg2);
}

export function LoadGenerationSession(arg1, arg2, arg3) {
  return window['go']['services']['ClientService']['LoadGenerationSession'](arg1, arg2, arg3);
}

export function MergeDocsIntoSource(arg1, arg2) {
  return window['go']['services']['ClientService']['MergeDocsIntoSource'](arg1, arg2);
}

export function RefineDocs(arg1, arg2, arg3) {
  return window['go']['services']['ClientService']['RefineDocs'](arg1, arg2, arg3);
}

export function Startup(arg1) {
  return window['go']['services']['ClientService']['Startup'](arg1);
}

export function StopStream(arg1, arg2) {
  return window['go']['services']['ClientService']['StopStream'](arg1, arg2);
}

export function UnbindSessionFromTab(arg1, arg2) {
  return window['go']['services']['ClientService']['UnbindSessionFromTab'](arg1, arg2);
}

export function ValidateBranchPair(arg1, arg2, arg3) {
  return window['go']['services']['ClientService']['ValidateBranchPair'](arg1, arg2, arg3);
}
