// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExploreDemo() {
  return window['go']['services']['ClientService']['ExploreDemo']();
}

export function GenerateDocs(arg1, arg2, arg3) {
  return window['go']['services']['ClientService']['GenerateDocs'](arg1, arg2, arg3);
}

export function Startup(arg1) {
  return window['go']['services']['ClientService']['Startup'](arg1);
}

export function StopStream() {
  return window['go']['services']['ClientService']['StopStream']();
}
