// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CommitDocs(arg1, arg2, arg3) {
  return window['go']['services']['ClientService']['CommitDocs'](arg1, arg2, arg3);
}

export function GenerateDocs(arg1, arg2, arg3, arg4) {
  return window['go']['services']['ClientService']['GenerateDocs'](arg1, arg2, arg3, arg4);
}

export function InitializeLLMClient(arg1) {
  return window['go']['services']['ClientService']['InitializeLLMClient'](arg1);
}

export function MergeDocsIntoSource(arg1, arg2) {
  return window['go']['services']['ClientService']['MergeDocsIntoSource'](arg1, arg2);
}

export function RefineDocs(arg1, arg2, arg3) {
  return window['go']['services']['ClientService']['RefineDocs'](arg1, arg2, arg3);
}

export function Startup(arg1) {
  return window['go']['services']['ClientService']['Startup'](arg1);
}

export function StopStream() {
  return window['go']['services']['ClientService']['StopStream']();
}
