// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';

export function CommitDocs(arg1:number,arg2:string,arg3:Array<string>):Promise<void>;

export function GenerateDocs(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string):Promise<models.DocGenerationResult>;

export function InitializeLLMClient(arg1:string):Promise<void>;

export function LoadGenerationSession(arg1:number,arg2:string,arg3:string):Promise<models.DocGenerationResult>;

export function MergeDocsIntoSource(arg1:number,arg2:string):Promise<void>;

export function RefineDocs(arg1:number,arg2:string,arg3:string):Promise<models.DocGenerationResult>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopStream():Promise<void>;
