// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckGitAvailability() {
  return window['go']['services']['FumadocsService']['CheckGitAvailability']();
}

export function CreateFumadocsProject(arg1) {
  return window['go']['services']['FumadocsService']['CreateFumadocsProject'](arg1);
}

export function Startup(arg1) {
  return window['go']['services']['FumadocsService']['Startup'](arg1);
}
