// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Delete(arg1, arg2, arg3) {
  return window['go']['services']['generationSessionService']['Delete'](arg1, arg2, arg3);
}

export function DeleteAll(arg1) {
  return window['go']['services']['generationSessionService']['DeleteAll'](arg1);
}

export function Get(arg1, arg2, arg3) {
  return window['go']['services']['generationSessionService']['Get'](arg1, arg2, arg3);
}

export function List(arg1) {
  return window['go']['services']['generationSessionService']['List'](arg1);
}

export function Startup(arg1) {
  return window['go']['services']['generationSessionService']['Startup'](arg1);
}

export function Upsert(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['services']['generationSessionService']['Upsert'](arg1, arg2, arg3, arg4, arg5);
}
