// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['services']['generationSessionService']['Create'](arg1);
}

export function DeleteAll(arg1) {
  return window['go']['services']['generationSessionService']['DeleteAll'](arg1);
}

export function DeleteByID(arg1) {
  return window['go']['services']['generationSessionService']['DeleteByID'](arg1);
}

export function GetByDocsBranch(arg1, arg2) {
  return window['go']['services']['generationSessionService']['GetByDocsBranch'](arg1, arg2);
}

export function GetByID(arg1) {
  return window['go']['services']['generationSessionService']['GetByID'](arg1);
}

export function List(arg1) {
  return window['go']['services']['generationSessionService']['List'](arg1);
}

export function Startup(arg1) {
  return window['go']['services']['generationSessionService']['Startup'](arg1);
}

export function UpdateByID(arg1, arg2) {
  return window['go']['services']['generationSessionService']['UpdateByID'](arg1, arg2);
}
