// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';

export function Create(arg1:models.GenerationSession):Promise<models.GenerationSession>;

export function DeleteAll(arg1:number):Promise<void>;

export function DeleteByID(arg1:number):Promise<void>;

export function GetByDocsBranch(arg1:number,arg2:string):Promise<models.GenerationSession>;

export function GetByID(arg1:number):Promise<models.GenerationSession>;

export function List(arg1:number):Promise<Array<models.GenerationSession>>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateByID(arg1:number,arg2:Record<string, any>):Promise<void>;
