// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Checkout(arg1, arg2) {
  return window['go']['services']['GitService']['Checkout'](arg1, arg2);
}

export function Clone(arg1, arg2) {
  return window['go']['services']['GitService']['Clone'](arg1, arg2);
}

export function DiffBetweenCommits(arg1, arg2, arg3) {
  return window['go']['services']['GitService']['DiffBetweenCommits'](arg1, arg2, arg3);
}

export function Init(arg1) {
  return window['go']['services']['GitService']['Init'](arg1);
}

export function LatestCommit(arg1) {
  return window['go']['services']['GitService']['LatestCommit'](arg1);
}

export function Open(arg1) {
  return window['go']['services']['GitService']['Open'](arg1);
}

export function Pull(arg1) {
  return window['go']['services']['GitService']['Pull'](arg1);
}

export function Push(arg1) {
  return window['go']['services']['GitService']['Push'](arg1);
}

export function Startup(arg1) {
  return window['go']['services']['GitService']['Startup'](arg1);
}

export function ValidateRepository(arg1) {
  return window['go']['services']['GitService']['ValidateRepository'](arg1);
}
