// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {git} from '../models';
import {plumbing} from '../models';
import {models} from '../models';
import {context} from '../models';

export function BranchExists(arg1:git.Repository,arg2:string):Promise<boolean>;

export function Checkout(arg1:git.Repository,arg2:string):Promise<void>;

export function Clone(arg1:string,arg2:string):Promise<git.Repository>;

export function Commit(arg1:git.Repository,arg2:string):Promise<plumbing.Hash>;

export function DeleteBranch(arg1:git.Repository,arg2:string):Promise<void>;

export function DeleteBranchByPath(arg1:string,arg2:string):Promise<void>;

export function DiffBetweenBranches(arg1:git.Repository,arg2:string,arg3:string):Promise<string>;

export function DiffBetweenCommits(arg1:git.Repository,arg2:string,arg3:string):Promise<string>;

export function GetCurrentBranch(arg1:string):Promise<string>;

export function HasUncommittedChanges(arg1:string):Promise<boolean>;

export function Init(arg1:string):Promise<git.Repository>;

export function LatestCommit(arg1:string):Promise<string>;

export function ListBranches(arg1:git.Repository):Promise<Array<models.BranchInfo>>;

export function ListBranchesByPath(arg1:string):Promise<Array<models.BranchInfo>>;

export function Open(arg1:string):Promise<git.Repository>;

export function Pull(arg1:git.Repository):Promise<void>;

export function Push(arg1:git.Repository):Promise<void>;

export function StageAll(arg1:git.Repository):Promise<void>;

export function StageFiles(arg1:git.Repository,arg2:Array<string>):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function ValidateRepository(arg1:string):Promise<void>;
