// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteApiKey(arg1) {
  return window['go']['services']['KeyringService']['DeleteApiKey'](arg1);
}

export function GetApiKey(arg1) {
  return window['go']['services']['KeyringService']['GetApiKey'](arg1);
}

export function ListApiKeys() {
  return window['go']['services']['KeyringService']['ListApiKeys']();
}

export function Startup() {
  return window['go']['services']['KeyringService']['Startup']();
}

export function StoreApiKey(arg1, arg2) {
  return window['go']['services']['KeyringService']['StoreApiKey'](arg1, arg2);
}
