// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {keyring} from '../models';

export function DeleteApiKey(arg1:keyring.Keyring,arg2:string):Promise<void>;

export function GetApiKey(arg1:keyring.Keyring,arg2:string):Promise<string>;

export function Startup():Promise<void>;

export function StoreApiKey(arg1:keyring.Keyring,arg2:string,arg3:Array<number>):Promise<void>;
