// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteApiKey(arg1:string):Promise<void>;

export function GetApiKey(arg1:string):Promise<string>;

export function ListApiKeys():Promise<Array<Record<string, string>>>;

export function StoreApiKey(arg1:string,arg2:Array<number>):Promise<void>;
