// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetModel(arg1) {
  return window['go']['services']['modelConfigService']['GetModel'](arg1);
}

export function ListModelGroups() {
  return window['go']['services']['modelConfigService']['ListModelGroups']();
}

export function SetModelEnabled(arg1, arg2) {
  return window['go']['services']['modelConfigService']['SetModelEnabled'](arg1, arg2);
}

export function SetProviderEnabled(arg1, arg2) {
  return window['go']['services']['modelConfigService']['SetProviderEnabled'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['services']['modelConfigService']['Startup'](arg1);
}
