// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';

export function GetModel(arg1:string):Promise<models.LLMModel>;

export function ListModelGroups():Promise<Array<models.LLMModelGroup>>;

export function SetModelEnabled(arg1:string,arg2:boolean):Promise<models.LLMModel>;

export function SetProviderEnabled(arg1:string,arg2:boolean):Promise<Array<models.LLMModel>>;

export function Startup(arg1:context.Context):Promise<void>;
