// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';

export function CheckLLMInstructions(arg1:number):Promise<boolean>;

export function Delete(arg1:number):Promise<void>;

export function Get(arg1:number):Promise<models.RepoLink>;

export function ImportLLMInstructions(arg1:number,arg2:string):Promise<void>;

export function LinkRepositories(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:string):Promise<void>;

export function List(arg1:number,arg2:number):Promise<Array<models.RepoLink>>;

export function Register(arg1:string,arg2:string,arg3:string):Promise<models.RepoLink>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateProjectPaths(arg1:number,arg2:string,arg3:string):Promise<void>;
