// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Get(arg1) {
  return window['go']['services']['repoLinkService']['Get'](arg1);
}

export function LinkRepositories(arg1, arg2, arg3, arg4) {
  return window['go']['services']['repoLinkService']['LinkRepositories'](arg1, arg2, arg3, arg4);
}

export function List(arg1, arg2) {
  return window['go']['services']['repoLinkService']['List'](arg1, arg2);
}

export function Register(arg1, arg2, arg3) {
  return window['go']['services']['repoLinkService']['Register'](arg1, arg2, arg3);
}

export function Startup(arg1) {
  return window['go']['services']['repoLinkService']['Startup'](arg1);
}
