// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckLLMInstructions(arg1) {
  return window['go']['services']['repoLinkService']['CheckLLMInstructions'](arg1);
}

export function Delete(arg1) {
  return window['go']['services']['repoLinkService']['Delete'](arg1);
}

export function Get(arg1) {
  return window['go']['services']['repoLinkService']['Get'](arg1);
}

export function ImportLLMInstructions(arg1, arg2) {
  return window['go']['services']['repoLinkService']['ImportLLMInstructions'](arg1, arg2);
}

export function LinkRepositories(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['services']['repoLinkService']['LinkRepositories'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function List(arg1, arg2) {
  return window['go']['services']['repoLinkService']['List'](arg1, arg2);
}

export function Register(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['services']['repoLinkService']['Register'](arg1, arg2, arg3, arg4, arg5);
}

export function Startup(arg1) {
  return window['go']['services']['repoLinkService']['Startup'](arg1);
}

export function UpdateProjectOrder(arg1) {
  return window['go']['services']['repoLinkService']['UpdateProjectOrder'](arg1);
}

export function UpdateProjectPaths(arg1, arg2, arg3, arg4) {
  return window['go']['services']['repoLinkService']['UpdateProjectPaths'](arg1, arg2, arg3, arg4);
}

export function ValidateDirectory(arg1) {
  return window['go']['services']['repoLinkService']['ValidateDirectory'](arg1);
}
