// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';

export function CreateTemplate(arg1:models.Template):Promise<models.Template>;

export function DeleteTemplate(arg1:number):Promise<void>;

export function GetTemplate(arg1:number):Promise<models.Template>;

export function ListTemplates():Promise<Array<models.Template>>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateTemplate(arg1:models.Template):Promise<models.Template>;
