// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTemplate(arg1) {
  return window['go']['services']['templateService']['CreateTemplate'](arg1);
}

export function DeleteTemplate(arg1) {
  return window['go']['services']['templateService']['DeleteTemplate'](arg1);
}

export function GetTemplate(arg1) {
  return window['go']['services']['templateService']['GetTemplate'](arg1);
}

export function ListTemplates() {
  return window['go']['services']['templateService']['ListTemplates']();
}

export function Startup(arg1) {
  return window['go']['services']['templateService']['Startup'](arg1);
}

export function UpdateTemplate(arg1) {
  return window['go']['services']['templateService']['UpdateTemplate'](arg1);
}
