// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Get(arg1) {
  return window['go']['services']['userService']['Get'](arg1);
}

export function Greet(arg1) {
  return window['go']['services']['userService']['Greet'](arg1);
}

export function List(arg1, arg2) {
  return window['go']['services']['userService']['List'](arg1, arg2);
}

export function Register(arg1) {
  return window['go']['services']['userService']['Register'](arg1);
}

export function Startup(arg1) {
  return window['go']['services']['userService']['Startup'](arg1);
}
