// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';

export function Get(arg1:number):Promise<models.User>;

export function Greet(arg1:string):Promise<string>;

export function List(arg1:number,arg2:number):Promise<Array<models.User>>;

export function Register(arg1:string):Promise<models.User>;

export function Startup(arg1:context.Context):Promise<void>;
