// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1:string):Promise<string>;

export function LinkRepositories(arg1:string,arg2:string):Promise<void>;

export function SelectDirectory():Promise<string>;

export function StartDemoEvents():Promise<void>;

export function StopDemoEvents():Promise<void>;
