// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppSettings() {
	return window["go"]["main"]["App"]["GetAppSettings"]();
}

export function Greet(arg1) {
	return window["go"]["main"]["App"]["Greet"](arg1);
}

export function InitGitRepo(arg1) {
	return window["go"]["main"]["App"]["InitGitRepo"](arg1);
}

export function LinkRepositories(arg1, arg2, arg3) {
	return window["go"]["main"]["App"]["LinkRepositories"](arg1, arg2, arg3);
}

export function SelectDirectory() {
	return window["go"]["main"]["App"]["SelectDirectory"]();
}

export function StartDemoEvents() {
	return window["go"]["main"]["App"]["StartDemoEvents"]();
}

export function StopDemoEvents() {
	return window["go"]["main"]["App"]["StopDemoEvents"]();
}
