// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function StartDemoEvents() {
  return window['go']['main']['App']['StartDemoEvents']();
}

export function StopDemoEvents() {
  return window['go']['main']['App']['StopDemoEvents']();
}
