// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetAppSettings():Promise<models.AppSettings>;

export function GetRepoLinks():Promise<Array<models.RepoLink>>;

export function Greet(arg1:string):Promise<string>;

export function LinkRepositories(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ListRepoBranches(arg1:string):Promise<Array<models.BranchInfo>>;

export function SelectDirectory():Promise<string>;

export function StartDemoEvents():Promise<void>;

export function StopDemoEvents():Promise<void>;

export function UpdateAppSettings(arg1:string,arg2:string):Promise<models.AppSettings>;
